package com.example.demo;
// Generated Aug 1, 2017 11:51:52 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MessageHeader generated by hbm2java
 */
@Entity
@Table(name = "message_header",
         catalog = "wafaa"
)
public class MessageHeader implements java.io.Serializable {

    private Integer messageId;
    private String name;
    private String email;
    private String website;
    private String subject;
    private String message;
    private String recordStatus;
    private Date recordAddDate;

    public MessageHeader() {
    }

    public MessageHeader(String name, String email, String website, String subject, String message, String recordStatus, Date recordAddDate) {
        this.name = name;
        this.email = email;
        this.website = website;
        this.subject = subject;
        this.message = message;
        this.recordStatus = recordStatus;
        this.recordAddDate = recordAddDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "MESSAGE_ID", unique = true, nullable = false)
    public Integer getMessageId() {
        return this.messageId;
    }

    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    @Column(name = "NAME", length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "EMAIL", length = 50)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "website", length = 50)
    public String getWebsite() {
        return this.website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    @Column(name = "subject", length = 50)
    public String getSubject() {
        return this.subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    @Column(name = "message", length = 500)
    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @Column(name = "record_status", length = 50)
    public String getRecordStatus() {
        return this.recordStatus;
    }

    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "record_add_date", length = 10)
    public Date getRecordAddDate() {
        return this.recordAddDate;
    }

    public void setRecordAddDate(Date recordAddDate) {
        this.recordAddDate = recordAddDate;
    }

}
